// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgHboUC7S6odiZhASvotukM3pEB1rGe3U',
    appId: '1:76169562986:web:a9ae88cdcf450a238a7313',
    messagingSenderId: '76169562986',
    projectId: 'company-app-udmey',
    authDomain: 'company-app-udmey.firebaseapp.com',
    storageBucket: 'company-app-udmey.appspot.com',
    measurementId: 'G-SEJ0SLTJKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrDqQYgWW3_G4nUWq07NAf7VJZbZA5-HA',
    appId: '1:76169562986:android:bb0bd55119a9f7e18a7313',
    messagingSenderId: '76169562986',
    projectId: 'company-app-udmey',
    storageBucket: 'company-app-udmey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjLwBaTcyWeV3i3wQd6Z6M6FHLQkKEN0',
    appId: '1:76169562986:ios:0ea7d7000f9877658a7313',
    messagingSenderId: '76169562986',
    projectId: 'company-app-udmey',
    storageBucket: 'company-app-udmey.appspot.com',
    iosBundleId: 'com.example.projectcompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkjLwBaTcyWeV3i3wQd6Z6M6FHLQkKEN0',
    appId: '1:76169562986:ios:eb39bf2e1309be848a7313',
    messagingSenderId: '76169562986',
    projectId: 'company-app-udmey',
    storageBucket: 'company-app-udmey.appspot.com',
    iosBundleId: 'com.example.projectcompany.RunnerTests',
  );
}
